env:
 JOB_NAME: "sample-job"
  
steps:
  - label: "Generating Unit test pipeline" 
    command: |
      cat <<- YAML | buildkite-agent pipeline upload 
        steps:
          - command: echo "--> Start of concurrency gate"
            concurrency_group: gate-$${JOB_NAME}
            concurrency: 1
            key: start-gate

      YAML
