steps:
  - label: "Example Test - pass"
    command: echo "Hello!"
    notify:
      - slack:
          channels:
            - "#stephanie_test"
            - "#stephanie_test"
          message: "hello test"
