env:
  GLOBAL_TIMEOUT: 60

steps:

  - label: "Unit Testss"
    key: "unit_tests"
    command: "echo test global timeoutsddssss"

  - trigger: "app-deploy"
    build:
      message: this commit should cAA$$A$ ause issues
                 

