env:
  GLOBAL_TIMEOUT: 60

steps:

  - label: "Unit Testsssssssssss"
    key: "unit_tests"
    command: "echo test global timeoutsddsssss"

  - trigger: "app-deploy"
    build:
      message: this commit should cAA$$A$ ause issues
                 

