steps:
  - plugins:
       - shellcheck#v1.1.2:
            files: scriptssssssddddfffssssssssssddddssssssssssssssssssssssss/*.sh
       - docker#v3.3.0:
            image: node
            workdir: /app
