env:
  GLOBAL_TIMEOUT: 60

steps:
  - command: |
         curl -H "Authorization: Bearer $BUILDKITE_API_TOKEN" \
              -X GET "https://api.buildkite.com/v2/organizations/$BUILDKITE_ORGANIZATION_SLUG/pipelines/$BUILDKITE_PIPELINE_SLUG/builds/$BUILDKITE_BUILD_NUMBER/jobs/$BUILDKITE_JOB_ID/log"
  - input: "Parameters"
    fields:
      - text: "APP_VERSION"
        hint: "Provide App Version if different from default"
        required: false
        key: app-version
  - label: "Unit Testsssss"
    key: "unit_tests"
    command: "echo test global timeoutsddssssss"

  - trigger: "app-deploy"
    build:
      message: this commit should cAA$$A$ ause issues

      
                 

