steps:
  - label: "Check changed files"
    plugins:
      - monorepo-diff#v1.0.1:
          watch:           
            - path: "src/"
              config:
                trigger: "app-deploy"
                label: "Triggered deploy"
                build:
                  message: this commit should cause issues
                  env:
                    - AWS_REGION=us-west-2
