steps:
  - block: APPROVE BUILD?
    key: "block-step"
  - command: |
      cat <<- YAML | buildkite-agent pipeline upload 
        steps:
          - label: Checking permission
            command: "if [[ \"$BUILDKITE_UNBLOCKER_TEAMS\" == *\"Production Approval\"* ]];
              then\n  make install\nelse \n  exit -1\nYAML\nfi\n"
            depends_on: "block-step"
      YAML
