on:
  push:
    branches:
    - main
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-22.04

    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v2.1.0"
        with:
          buildkite_api_access_token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }} 
          pipeline: "atte-test-org-1/first"
          branch: "main"
          commit: "HEAD"
          message:  ":github: Triggered from a GitHub Action"
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true     
          send_pull_request: true
