on:
  issue_comment:
    types: [ created, edited ]
    
jobs:
  is_pr_comment:
    name: Check for Pull Request comment slash commands
    if: ${{ github.event.issue.pull_request }} &&  {contains(github.event.comment.body, '/bk retry')} # makes sure we're looking at a pull request comment
    runs-on: ubuntu-latest
    
    steps:
      - name: Extract Build Information
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "COMMENT_BODY"
       
