on:
  issue_comment:
    types: [ created, edited ]
    
jobs:
  is_pr_comment:
    name: Check for Pull Request comment slash commands
    if: ${{ github.event.issue.pull_request }} &&  {contains(github.event.comment.body, '/bk retry')} # makes sure we're looking at a pull request comment
    runs-on: ubuntu-latest
    
    steps:
     - name: Fetch PR Details
        id: pr_details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_API_URL="${{ github.event.issue.pull_request.url }}"
          PR_DETAILS=$(curl -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github.v3+json" $PR_API_URL)
          echo $PR_DETAILS
          echo "::set-output name=branch::$(echo $PR_DETAILS | jq -r .head.ref)"
          echo "::set-output name=sha::$(echo $PR_DETAILS | jq -r .head.sha)"
