on:
  issue_comment:
    types: [ created, edited ]
jobs:
  is_pr_comment:
    name: Check for Pull Request comment slash commands
    if: ${{ github.event.issue.pull_request }} # makes sure we're looking at a pull request comment
    runs-on: ubuntu-latest
    
    steps:
      - name: Retry Build with /bk retry
        if: contains(github.event.comment.body, '/bk retry') #
        uses: "buildkite/trigger-pipeline-action@v2.1.0"
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          echo "COMMENT_BODY"
        with:
          buildkite_api_access_token: ${{ secrets.BK_SECRET }} 
          pipeline: "atte-test-org-1/first"
          branch: "main"
          commit: "HEAD"
          message:  ":github: Triggered from a GitHub Action"
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true     
          send_pull_request: true
